import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Asset, Dependency, BackupInfo, Workflow, Scenario } from '@/db/types'
import { computeCascade, findSinglePointsOfFailure } from './graph-engine'

interface PlanData {
  businessName: string
  assets: Asset[]
  dependencies: Dependency[]
  backups: BackupInfo[]
  workflows: Workflow[]
  scenarios: Scenario[]
}

export function generateRecoveryPlanPDF(data: PlanData) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = margin

  const backupMap = new Map(data.backups.map((b) => [b.assetId, b]))
  const assetMap = new Map(data.assets.map((a) => [a.id, a]))

  function addPage() {
    doc.addPage()
    y = margin
  }

  function checkSpace(needed: number) {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      addPage()
    }
  }

  function heading(text: string, size: number = 16) {
    checkSpace(20)
    doc.setFontSize(size)
    doc.setFont('helvetica', 'bold')
    doc.text(text, margin, y)
    y += size * 0.6 + 4
  }

  function bodyText(text: string, indent: number = 0) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2 - indent)
    checkSpace(lines.length * 5 + 2)
    doc.text(lines, margin + indent, y)
    y += lines.length * 5 + 2
  }


  // === COVER PAGE ===
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text('Business Continuity', pageWidth / 2, 80, { align: 'center' })
  doc.text('& Disaster Recovery Plan', pageWidth / 2, 94, { align: 'center' })

  doc.setFontSize(18)
  doc.setFont('helvetica', 'normal')
  doc.text(data.businessName || 'Unnamed Business', pageWidth / 2, 120, {
    align: 'center',
  })

  doc.setFontSize(12)
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 140, {
    align: 'center',
  })

  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text('Generated by PumaResilience BCP/DR Planning Tool', pageWidth / 2, 270, {
    align: 'center',
  })
  doc.setTextColor(0)

  // === EXECUTIVE SUMMARY ===
  addPage()
  heading('Executive Summary', 20)
  y += 4

  const criticalAssets = data.assets.filter((a) => a.criticality === 'Critical')
  const assetsWithBackup = data.assets.filter(
    (a) => backupMap.get(a.id)?.hasBackup === 'Yes'
  )
  const spofs = findSinglePointsOfFailure(data.assets, data.dependencies)
  const completedScenarios = data.scenarios.filter((s) => s.status === 'Completed')
  const coverage = data.assets.length > 0
    ? Math.round((assetsWithBackup.length / data.assets.length) * 100)
    : 0

  bodyText(`This plan covers ${data.assets.length} technology assets, of which ${criticalAssets.length} are classified as critical.`)
  bodyText(`Backup coverage: ${coverage}% (${assetsWithBackup.length} of ${data.assets.length} assets have documented backups).`)
  bodyText(`${data.dependencies.length} dependencies mapped, with ${spofs.length} single point(s) of failure identified.`)
  bodyText(`${completedScenarios.length} of ${data.scenarios.length} tabletop exercises completed.`)
  bodyText(`${data.workflows.length} business workflows documented.`)

  if (spofs.length > 0) {
    y += 4
    bodyText('Single Points of Failure:')
    for (const { asset, downstreamCount } of spofs.slice(0, 10)) {
      bodyText(`- ${asset.name} (${asset.criticality}) — ${downstreamCount} downstream asset(s) affected`, 4)
    }
  }

  // === TECHNOLOGY INVENTORY ===
  addPage()
  heading('Technology Inventory', 20)
  y += 2

  const assetRows = data.assets
    .sort((a, b) => {
      const order: Record<string, number> = { Critical: 0, High: 1, Medium: 2, Low: 3 }
      return (order[a.criticality] ?? 4) - (order[b.criticality] ?? 4)
    })
    .map((a) => {
      const backup = backupMap.get(a.id)
      const backupStatus = !backup
        ? 'Not documented'
        : backup.hasBackup === 'Yes'
          ? `Yes (${backup.backupMethod})`
          : backup.hasBackup === 'No'
            ? 'NO BACKUP'
            : 'Unknown'
      return [
        a.name,
        a.category,
        a.criticality,
        a.vendor || '-',
        a.ownerName || '-',
        backupStatus,
      ]
    })

  autoTable(doc, {
    startY: y,
    head: [['Asset', 'Category', 'Criticality', 'Vendor', 'Owner', 'Backup']],
    body: assetRows,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 30, 30] },
    margin: { left: margin, right: margin },
  })
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 10

  // === DEPENDENCY MAP ===
  checkSpace(40)
  heading('Dependency Map', 20)
  y += 2

  if (data.dependencies.length === 0) {
    bodyText('No dependencies have been mapped.')
  } else {
    const depRows = data.dependencies.map((d) => {
      const up = assetMap.get(d.upstreamAssetId)
      const down = assetMap.get(d.downstreamAssetId)
      return [
        up?.name ?? 'Unknown',
        down?.name ?? 'Unknown',
        d.dependencyType,
        d.description || '-',
      ]
    })

    autoTable(doc, {
      startY: y,
      head: [['Upstream (depended on)', 'Downstream (affected)', 'Type', 'Description']],
      body: depRows,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [30, 30, 30] },
      margin: { left: margin, right: margin },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 10
  }

  // === BACKUP DETAILS ===
  addPage()
  heading('Backup Status', 20)
  y += 2

  for (const asset of data.assets.filter((a) => a.criticality === 'Critical' || a.criticality === 'High')) {
    const backup = backupMap.get(asset.id)
    checkSpace(40)
    heading(asset.name, 12)

    if (!backup || backup.hasBackup !== 'Yes') {
      bodyText(`STATUS: ${!backup ? 'Not documented' : backup.hasBackup === 'No' ? 'NO BACKUP' : 'Unknown'}`, 4)
    } else {
      bodyText(`Method: ${backup.backupMethod}`, 4)
      if (backup.backupLocation) bodyText(`Location: ${backup.backupLocation}`, 4)
      if (backup.backupFrequency) bodyText(`Frequency: ${backup.backupFrequency}`, 4)
      if (backup.estimatedRestoreTime) bodyText(`Estimated restore time: ${backup.estimatedRestoreTime}`, 4)
      if (backup.lastVerifiedDate) bodyText(`Last verified: ${backup.lastVerifiedDate}`, 4)
      if (backup.lastTestRestoreDate) bodyText(`Last test restore: ${backup.lastTestRestoreDate}`, 4)
      if (backup.restoreSteps) {
        bodyText('Restore steps:', 4)
        bodyText(backup.restoreSteps, 8)
      }
    }
    y += 2
  }

  // === BUSINESS WORKFLOWS ===
  if (data.workflows.length > 0) {
    addPage()
    heading('Business Workflows', 20)
    y += 2

    for (const wf of data.workflows) {
      checkSpace(50)
      heading(wf.name, 12)
      if (wf.description) bodyText(wf.description, 4)
      bodyText(`Criticality: ${wf.criticality}`, 4)
      if (wf.maxTolerableDowntime) bodyText(`Max tolerable downtime: ${wf.maxTolerableDowntime}`, 4)
      if (wf.revenueImpactDescription) bodyText(`Revenue impact: ${wf.revenueImpactDescription}`, 4)
      if (wf.manualWorkaround) {
        bodyText('Manual workaround:', 4)
        bodyText(wf.manualWorkaround, 8)
      }
      const linkedAssets = wf.assetIds
        .map((id) => assetMap.get(id)?.name)
        .filter(Boolean)
      if (linkedAssets.length > 0) {
        bodyText(`Depends on: ${linkedAssets.join(', ')}`, 4)
      }
      y += 4
    }
  }

  // === SCENARIO RECOVERY PLANS ===
  for (const scenario of data.scenarios) {
    addPage()
    heading(`Scenario: ${scenario.name}`, 18)
    y += 2

    bodyText(`Type: ${scenario.scenarioType}`)
    bodyText(`Status: ${scenario.status}`)
    y += 2

    heading('The Scenario', 12)
    bodyText(scenario.triggerDescription)
    y += 2

    // Impact
    if (scenario.initiallyAffectedAssetIds.length > 0) {
      heading('Impact Assessment', 12)
      const cascade = computeCascade(
        scenario.initiallyAffectedAssetIds,
        data.assets,
        data.dependencies
      )

      const directNames = scenario.initiallyAffectedAssetIds
        .map((id) => assetMap.get(id)?.name ?? 'Unknown')
        .join(', ')
      bodyText(`Directly affected: ${directNames}`)

      const downstreamIds = cascade.affectedAssetIds.filter(
        (id) => !scenario.initiallyAffectedAssetIds.includes(id)
      )
      if (downstreamIds.length > 0) {
        const downstreamNames = downstreamIds
          .map((id) => assetMap.get(id)?.name ?? 'Unknown')
          .join(', ')
        bodyText(`Cascade effects: ${downstreamNames}`)
      }
      bodyText(`Total affected: ${cascade.affectedAssetIds.length} asset(s)`)
      y += 2
    }

    // Discussion prompts
    if (scenario.discussionPrompts.length > 0) {
      heading('Discussion Prompts', 12)
      for (const prompt of scenario.discussionPrompts) {
        bodyText(`- ${prompt}`, 4)
      }
      y += 2
    }

    // Recovery steps
    if (scenario.recoverySteps.length > 0) {
      heading('Recovery Steps', 12)
      for (let i = 0; i < scenario.recoverySteps.length; i++) {
        const step = scenario.recoverySteps[i]
        checkSpace(20)
        bodyText(`${i + 1}. ${step.action}`, 4)
        if (step.responsiblePerson) bodyText(`   Who: ${step.responsiblePerson}`, 8)
        if (step.estimatedDuration) bodyText(`   Time: ${step.estimatedDuration}`, 8)
      }
      y += 2
    }

    // Exercise notes
    if (scenario.exerciseNotes) {
      heading('Exercise Notes & Action Items', 12)
      bodyText(scenario.exerciseNotes)
    }
  }

  // === CONTACT DIRECTORY ===
  addPage()
  heading('Contact Directory', 20)
  y += 2

  const contacts = data.assets
    .filter((a) => a.ownerName)
    .map((a) => [
      a.ownerName,
      a.name,
      a.ownerEmail || '-',
      a.ownerPhone || '-',
    ])

  if (contacts.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Contact', 'Responsible For', 'Email', 'Phone']],
      body: contacts,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [30, 30, 30] },
      margin: { left: margin, right: margin },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 10
  } else {
    bodyText('No contacts documented. Assign owners to assets to populate this section.')
  }

  // Vendor support
  checkSpace(40)
  heading('Vendor Support Contacts', 14)
  y += 2

  const vendorRows = data.assets
    .filter((a) => a.vendor || a.vendorSupportPhone || a.vendorSupportUrl)
    .map((a) => [
      a.name,
      a.vendor || '-',
      a.vendorSupportPhone || '-',
      a.vendorSupportUrl || '-',
    ])

  if (vendorRows.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Asset', 'Vendor', 'Support Phone', 'Support URL']],
      body: vendorRows,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [30, 30, 30] },
      margin: { left: margin, right: margin },
      columnStyles: { 3: { cellWidth: 55 } },
    })
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `${data.businessName || 'Business'} — BCP/DR Plan — Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
    doc.text(
      `Generated ${new Date().toLocaleDateString()}`,
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    )
    doc.setTextColor(0)
  }

  // Download
  const timestamp = new Date().toISOString().slice(0, 10)
  doc.save(`recovery-plan-${timestamp}.pdf`)
}
